[package]
name = "alopt"
version = "0.1.0"
edition = "2024"

[features]
# default = ["tracing"]
tracing = ["dep:tracing"]
tokio = ["dep:tokio", "async"]
async = []

[dependencies]
ringbuffer = "0.15.0"
tokio = { version = "1.44.0", features = ["sync"], optional = true }
tracing = { version = "0.1.41", optional = true }
